services:
  nginx-conf:
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-conf:
    volumes:
      - .:/var/www

  mysql-conf:
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql/8.0/payment:/var/lib/mysql:rw